
replicaCount: 1

image:
  repository: manashwi/reactapp
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

service:
  type: NodePort
  port: 80
  nodePort: 31231





secrets:
  prometheus: <path:kv-avp-test-1234#federation>
  instana: <path:kv-avp-test-1234#instana>
