apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "myfirstchart.fullname" . }}
  labels:
    {{- include "myfirstchart.labels" . | nindent 4 }}

spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "myfirstchart.selectorLabels" . | nindent 6 }}

  template:
    metadata:
      labels:
        {{- include "myfirstchart.selectorLabels" . | nindent 8 }}

    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ default .Chart.AppVersion .Values.image.tag }}"
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}

          volumeMounts:
            - name: secret-volume
              mountPath: /etc/secrets
              readOnly: true

      volumes:
        - name: secret-volume
          secret:
            secretName: test-secrets
